import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faChevronDown,
  faGlobe,
  faEnvelope,
  faBuilding,
  faTimes,
  faBars,
  faArrowLeft,
  faMapMarkerAlt,
  faGraduationCap,
  faGift,
  faCalendar,
  faHeart,
  faBriefcase,
  faLightbulb,
  faCode,
  faChevronLeft,
  faChevronRight,
  faPaperPlane,
  faIdCard,
  faShieldHalved,
  faMobileScreen,
  faRocket,
  faUsers,
} from '@fortawesome/free-solid-svg-icons';
import {
  faInstagram,
  faFacebook,
  faTiktok,
  faYoutube,
  faLinkedin,
  faGooglePlay,
  faApple,
} from '@fortawesome/free-brands-svg-icons';

library.add(
  faChevronDown,
  faGlobe,
  faEnvelope,
  faBuilding,
  faTimes,
  faBars,
  faArrowLeft,
  faMapMarkerAlt,
  faGraduationCap,
  faGift,
  faCalendar,
  faHeart,
  faBriefcase,
  faLightbulb,
  faCode,
  faChevronLeft,
  faChevronRight,
  faPaperPlane,
  faIdCard,
  faShieldHalved,
  faMobileScreen,
  faRocket,
  faUsers,
  faInstagram,
  faFacebook,
  faTiktok,
  faYoutube,
  faLinkedin,
  faGooglePlay,
  faApple,
);
